### ISSUE TITLE
.gitignore should include vendor

### ISSUE THREAD

**Issue by selfmanagingresource** [GoogleContainerTools/kpt-config-sync#1]
After building config-sync following the instructions `git status` has a big vendor dir. We  should include a .gitignore to improve the out of box developer experience.

**Comment by mortent** [comment]
@selfmanagingresource I will take a look at it.

**Comment by karlkfi** [comment]
@selfmanagingresource is this still a problem? I'm pretty sure the vendoring is now required and validated by CI, so it should be up to date. Re-building shouldn't change it.
