### ISSUE TITLE
After updating git-creds secret, I'm forced to recreate the rootsync pod

### ISSUE THREAD

**Issue by samirtahir91** [GoogleContainerTools/kpt-config-sync#1188]
Hi, 

If I update the token in a git-creds secret being consumed by a RootSync, I have to manually delete the pod for it to pick up the new secret token on recreate, or revoke the token and wait for it to crash and restart.

I can see the reconcile for a rootsync is triggered on change to the git secret here: https://github.com/GoogleContainerTools/kpt-config-sync/blob/b920ba45ef00cadf5362dfbe7c42eb44ec8e0902/pkg/reconcilermanager/controllers/rootsync_controller.go#L638

But assume since the rootsync object is unchanged, nothing meaningful actually happens if I modify the secret?

Can you either:
1. Modify the git-sync to dynamically fetch the new the token if the secret is updated? Would help a lot (my use case involves renewing a token frequently)
2. Force the rootsync pod to be recreated on a git-creds secret modification event.

Thanks

Samir

**Comment by karlkfi** [comment]
This is the standard k8s behavior for secrets and deployments. If you want a deployment to pick up a change in a secret, you usually have to update the deployment. The conventional way to do this is to test Secrets an immutable, create a new secret, and update the reference in the deployment, or in this case the RootSync/RepoSync.

**Comment by samirtahir91** [comment]
Thanks for the reply, can you explain what is the purpose to reconcile the RootSync if the git-creds secret is modified?

**Comment by karlkfi** [comment]
The reconciler-manager watches the RootSync/RepoSync and updates the reconciler deployment when it changes. But if only the Secret contents changed, that doesn't change the reconciler deployment spec, so the pod doesn't get replaced and it doesn't pick up the new secret. If you want the reconciler spec to change you can change the RootSync/RepoSync to reference a new secret.

**Comment by samirtahir91** [comment]
> The reconciler-manager watches the RootSync/RepoSync and updates the reconciler deployment when it changes. But if only the Secret contents changed, that doesn't change the reconciler deployment spec, so the pod doesn't get replaced and it doesn't pick up the new secret. If you want the reconciler spec to change you can change the RootSync/RepoSync to reference a new secret.

I understand this, I guess my point is why watch the secret at all and reconcile the RootSync on secret update events, updates to a RootSync will trigger a reconcile anyhow, so is this redundant/misleading?
https://github.com/GoogleContainerTools/kpt-config-sync/blob/b920ba45ef00cadf5362dfbe7c42eb44ec8e0902/pkg/reconcilermanager/controllers/rootsync_controller.go#L638

**Comment by karlkfi** [comment]
I think the secret keys are validated by the reconciler-manager to confirm the correct keys are set, so that errors can be added to the RSync status. 

For RepoSyncs, the Secret is also copied from the tenant namespace to the config-management-system namespace so they can be loaded into the reconciler.

It might be possible that we could add some way to modify the reconciler deployment to pick up new secret changes, but this behavior does not exist today. Today, if the secret name doesn't change, the deployment spec doesn't change.

Sometimes people use annotations with a hash of the secret manifest or an update timestamp to force pick up of changes to mutable dependencies, but Config Sync doesn't do this today.

Creating a new secret when you need to update it is the preferred method.

**Comment by samirtahir91** [comment]
> I think the secret keys are validated by the reconciler-manager to confirm the correct keys are set, so that errors can be added to the RSync status.
> 
> For RepoSyncs, the Secret is also copied from the tenant namespace to the config-management-system namespace so they can be loaded into the reconciler.
> 
> It might be possible that we could add some way to modify the reconciler deployment to pick up new secret changes, but this behavior does not exist today. Today, if the secret name doesn't change, the deployment spec doesn't change.
> 
> Sometimes people use annotations with a hash of the secret manifest or an update timestamp to force pick up of changes to mutable dependencies, but Config Sync doesn't do this today.
> 
> Creating a new secret when you need to update it is the preferred method.

Ok got it thanks.

I think it would be a good feature to add for RootSyncs.

For now I am automating token renewal in the secret and deleting the RootSyncs matching a certain label, but I feel it could be better to have this behaviour in config sync itself. 

Is there any negatives to deleting a rootsync pod to force an update of the secret on new pod creation?

**Comment by karlkfi** [comment]
Evicting a pod is always going to be safer than just deleting it, because it allows for graceful shutdown. But unfortunately there's no kubectl command for that. You can either craft a kubectl api call, use kubectl rollout, or use the kubectl-evict plugin.

**Comment by samirtahir91** [comment]
Ok thanks for the suggestions
