### ISSUE TITLE
Namespaces not included in OSS-release yaml

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleContainerTools/kpt-config-sync#127]
Hi,

I downloaded the latest release yaml (https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v1.13.0/config-sync-manifest.yaml) and it did not include the Namespace definitions where it needs to be deployed.

I did find the release-oss script though where it states that it needs to include those, so probably somewhere something went wrong while running this script on the last release. Could this be validated?

Kind regards,
Wietse

**Comment by sdowell** [comment]
Thank you for reporting this issue, I'll look into this

**Comment by sdowell** [comment]
A fix has been applied which will include the missing resources for future releases. The `v1.13.0` release has also been updated to include the missing resources. Thank you for your bug report!

**Comment by wmuizelaar** [comment]
That is a real quick and nice response, I can confirm it works. Thanks!
