### ISSUE TITLE
Update contribution guide

### ISSUE THREAD

**Issue by sdowell** [GoogleContainerTools/kpt-config-sync#18]
The [contribution guide](https://github.com/GoogleContainerTools/kpt-config-sync/blob/main/docs/contributing.md) needs to be updated now that development is happening on Github.

**Comment by mikebz** [comment]
General parameters for a guideline here:
1) when a contributor is signing up for a feature or a bug - how do they know that their work will land?  Common failure modes: (a) working on a problem that the core team is already working on (b) working on a solution that does not align with the general technical direction of the system (c) not getting timely PR review and merge.
2) where should the discussion take place?  Where do the core contributors look and what do they pay attention to?  It could be Slack, email, discussions, issues etc.  
3) what's the overall lifecycle of a contribution - what do we expect to be done by who and when?
