### ISSUE TITLE
Support for multiple RootSyncs managing resources in the same implicit namespace

### ISSUE THREAD

**Issue by tomasaschan** [GoogleContainerTools/kpt-config-sync#207]
We have a setup where we have multiple `RootSync`s fighting for control over the same namespace. Simplified, the setup looks something like this:

* A `RootSync` named `sync-a` declares `namespace-a` explicitly
* A `RootSync` named `sync-x` declares resources in `namespace-a`, but not `namespace-a` itself
* A `RootSync` named `sync-y` also declares resources in `namespace-a`, but not `namespace-a` itself
* A `RootSync` named `root` declares all the above `RootSync`s

Since we create all of `sync-{a,x,y}` with git-ops (managed by `root`) we don't have any control of the order in which they are reconciled. _If_ either of `sync-x` or `sync-y` manage to create `namespace-a` before `sync-a` does, then they will assume ownership, and `sync-a` will no longer be allowed to create it (and as a result, all its dependent resources also fail to be created).

(Creating this as a separate issue to have something to refer to from a design doc I'm adding as a companion to #191.)

**Comment by sdowell** [comment]
@tomasaschan Is your setup using the admission webhook?

**Comment by mikebz** [comment]
@tomasaschan thinking out loud here - is it possible to change sync-x and sync-y to be RepoSyncs?  Also we do have a dependsOn annotation that can help with sequencing here.

**Comment by tomasaschan** [comment]
@mikebz I'm on parental leave until after summer, so I'm a bit out of the loop here. I recommend you reach out to the team in the config mgmt SIG.

**Comment by tomasaschan** [comment]
Back from parental leave!

And in short:

* No, changing them to be `RepoSync`s is not an option here. A concrete use case we have is that we install Prometheus in `prometheus-system` using one `RootSync` (which declares the namespace explicitly, corresponding to `sync-x`  in the example), and then we have other infrastructure components which install cluster-scoped components where we also want to add a `ServiceMonitor` in the `prometheus-system` namespace; we'd rather have the `ServicveMonitor` resources declared and managed together with the thing they monitor, rather than with the Prometheus infra.

* No, dependencies doesn't help here since it doesn't support depending on things managed in different `*Sync`s.

**Comment by sdowell** [comment]
Implemented by https://github.com/GoogleContainerTools/kpt-config-sync/pull/883
