### ISSUE TITLE
Is `nomos` supposed to work when using OSS CS?

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleContainerTools/kpt-config-sync#226]
If I install CS like this:
```
CONFIG_SYNC_VERSION=1.13.0
kubectl apply \
    -f https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v${CONFIG_SYNC_VERSION}/config-sync-manifest.yaml \
    --wait
```
And then deploy my `RootSyncs` and `RepoSyncs`, my resources are successfully synced, etc. no problem.

But if I run `nomos status --contexts $(k config current-context)`, I'm getting this error:
```
NOT INSTALLED   The ACM operator is neither installed in the "kube-system" namespace nor the "config-management-system" namespace
```
Is `nomos` supposed to work when installing/using OSS CS?

I'm locally with `nomos --version`: `v1.13.0-rc.7`, that I installed like this:
```
curl -L https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v${CONFIG_SYNC_VERSION}/nomos_linux_amd64 > nomos
chmod +x nomos
```

**Comment by sdowell** [comment]
Thank you for your post!

It appears that `nomos status` is currently designed to use the ACM operator. I think it would be a reasonable feature request to make it work with OSS Config Sync
