### ISSUE TITLE
Feature Request: Capability to delete underlying objects when RootSync (or RepoSync) is deleted.

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt-config-sync#340]
It will be nice if I can manage the entire lifecycle of kubernetes object through a RootSync object. Today, when I delete a RootSync object, the underlying objects (contained in the git repo specified in the RootSync) are not deleted which is a nice default behavior given that it can be disruptive. However, there are some use-cases where I would like the underlying objects to be deleted when the RootSync object that was managing them is deleted.

My current use-cases are primarily driven by tests/automation.

/cc @karlkfi @sdowell

**Comment by mikebz** [comment]
I believe @karlkfi is working on this and I think it's merged: #242

**Comment by karlkfi** [comment]
The [Deletion Propagation](https://github.com/GoogleContainerTools/kpt-config-sync/blob/main/docs/deletion-propagation.md) feature will be in v1.15.0. Use the `configsync.gke.io/deletion-propagation-policy: Foreground` annotation on a RootSync/RepoSync to enable it.
