### ISSUE TITLE
Project not importable in other Go projects

### ISSUE THREAD

**Issue by tomasaschan** [GoogleContainerTools/kpt-config-sync#4]
I want to build a controller that watches for `RootSync` objects, and tried to add 
```
import configsync "kpt.dev/configsync/pkg/api/v1beta1"
```
at the top of the controller file.

However, then `go mod tidy` fails with this error, which seems like it should be fixable (it refers to files in `examples` which might not have to be bundled with the package, or named like this?):
```
 λ go mod tidy
go: finding module for package kpt.dev/configsync/pkg/api/v1beta1
go: downloading kpt.dev/configsync v0.0.0-20220719182314-469c8ee811cc
<redacted>/controllers imports
        kpt.dev/configsync/pkg/api/v1beta1: create zip: examples/kubevirt-compiled/clusterrole_kubevirt.io:operator.yaml: malformed file path "examples/kubevirt-compiled/clusterrole_kubevirt.io:operator.yaml": invalid char ':'
examples/kubevirt/cluster/kubevirt.io:operator-clusterrole.yaml: malformed file path "examples/kubevirt/cluster/kubevirt.io:operator-clusterrole.yaml": invalid char ':'
```

**Comment by janetkuo** [comment]
cc @mortent @mikebz

**Comment by janetkuo** [comment]
It seems that we could fix this by renaming [clusterrole_kubevirt.io:operator.yaml](https://github.com/GoogleContainerTools/kpt-config-sync/blob/e14fa0b41192fce56ee27be2171bf349159c7c36/examples/kubevirt-compiled/clusterrole_kubevirt.io:operator.yaml) and [kubevirt.io:operator-clusterrole.yaml](https://github.com/GoogleContainerTools/kpt-config-sync/blob/e14fa0b41192fce56ee27be2171bf349159c7c36/examples/kubevirt/cluster/kubevirt.io:operator-clusterrole.yaml).

**Comment by sdowell** [comment]
I'll take a look

**Comment by mikebz** [comment]
this is fixed:
```
go  mod tidy
go: finding module for package kpt.dev/configsync/pkg/api/configsync/v1beta1
go: downloading kpt.dev/configsync v0.0.0-20220812180759-434145413977
go: found kpt.dev/configsync/pkg/api/configsync/v1beta1 in kpt.dev/configsync v0.0.0-20220812180759-434145413977
```
