### ISSUE TITLE
Large number of errors in otel-collector

### ISSUE THREAD

**Issue by itsavvy-ankur** [GoogleContainerTools/kpt-config-sync#927]
Large number of errors appear from otel-collector. We are running ACM v1.16.1 and are using the default config maps without modifications for the collector config. 
-- also see related issue https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/707

  "textPayload": "2023-10-07T21:14:36.250Z\terror\texporterhelper/queued_retry.go:149\tExporting failed. Try enabling retry_on_failure config option to retry on retryable errors\t{\"kind\": \"exporter\", \"data_type\": \"metrics\", \"name\": \"googlecloud/kubernetes\", \"error\": \"failed to export time series to GCM: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Unrecognized metric labels: [configsync_sync_namespace], [configsync_sync_name], [configsync_sync_kind]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_namespace], [configsync_sync_name]; Unrecognized metric labels: [configsync_sync_name], [configsync_sync_namespace], [configsync_sync_kind]; Unrecognized metric labels: [configsync_sync_namespace], [configsync_sync_kind], [configsync_sync_name]; Unrecognized metric labels: [configsync_sync_namespace], [configsync_sync_name], [configsync_sync_kind]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_name], [configsync_sync_namespace]; Unrecognized metric labels: [configsync_sync_namespace], [configsync_sync_name], [configsync_sync_kind]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_name], [configsync_sync_namespace]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_name], [configsync_sync_namespace]; Unrecognized metric labels: [configsync_sync_namespace], [configsync_sync_name], [configsync_sync_kind]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_name], [configsync_sync_namespace]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_namespace], [configsync_sync_name]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_name], [configsync_sync_namespace]; Unrecognized metric labels: [configsync_sync_kind], [configsync_sync_namespace], [configsync_sync_name]\\nerror details: name = Unknown desc = total_point_count:14 errors:{status:{code:3} point_count:14}\"}",

**Comment by tiffanny29631** [comment]
Hi, thanks for raising the issue. This bug has been fixed with the latest release v1.17.2, please upgrade and let us know if error is cleared.
