### ISSUE TITLE
Make it possible to reconcile RootSyncs without cluster-admin

### ISSUE THREAD

**Issue by tomasaschan** [GoogleContainerTools/kpt-config-sync#935]
We've recently started working on slimming down the permissions we grant to `RootSync`s that target repositories we are not in control of, but realized whatever permissions we grant are going to be effectively ignored, as `reconciler-manager` [is hard-coded to grant `cluster-admin` to root reconcilers](https://github.com/GoogleContainerTools/kpt-config-sync/blob/199db6dbfa0b9eb1824925c8c687574de095a294/pkg/reconcilermanager/controllers/rootsync_controller.go#L789).

I could think of a few options for how to configure that would work for us, so would like to hear your thoughts on what you'd prefer before I submit a design proposal and/or PR:

* A boolean property, defaulting to `false`, which just turns off creating the `ClusterRoleBinding` entirely. If a user turns this on, they are responsible for creating a `ClusterRole` and binding it to the KSA.  
  Example: `.spec.overrides.manuallyManagePermissions: true` (name very much pending)

* A string property denoting which role to grant to the KSA. If provided `reconciler-manager` then creates a `ClusterRoleBinding` to that role instead of `cluster-admin`.  
  Example: `.spec.overrides.reconcilerClusterRole: my-config-sync-role`

* A string property denoting a different KSA to use rather than the one currently created by the `reconciler-manager`. If provided, neither the KSA nor the `ClusterRoleBinding` would be created (i.e. [these lines would be skipped](https://github.com/GoogleContainerTools/kpt-config-sync/blob/199db6dbfa0b9eb1824925c8c687574de095a294/pkg/reconcilermanager/controllers/rootsync_controller.go#L205-L212)); the onus to do that would be on the user instead. (In addition, [these lines](https://github.com/GoogleContainerTools/kpt-config-sync/blob/199db6dbfa0b9eb1824925c8c687574de095a294/pkg/reconcilermanager/controllers/rootsync_controller.go#L914-L918) would have to be made aware of the override).
  
  Example: `.spec.overrides.serviceAccountName: my-own-ksa`

Would you accept a feature contribution that makes this configurable? If so, is there one of the approaches above (or something else entirely) you prefer?

**Comment by sdowell** [comment]
@tomasaschan Thank you for filing this issue - this seems like a reasonable feature request IMO. We would gladly accept a feature contribution to make this configurable - and after some offline discussion we are leaning towards the second option you proposed (configurable ClusterRole).

My reasoning is that this provides a more user friendly UX compared to the first and third options. The first and third option require for the user to manage the creation/lifecycle of the ClusterRoleBindings for every reconciler/KSA. With the second option, the user just needs to create the ClusterRole and Config Sync will manage the creation/lifecycle of the ClusterRoleBindings. This approach also can easily be backwards compatible by defaulting to `cluster-admin`.

I think the next step would be to go a bit more into detail with a design doc. Would you be open to contributing a design doc for this feature?
