### ISSUE TITLE
Breaking changes should be announced in release notes

### ISSUE THREAD

**Issue by szihai** [GoogleContainerTools/kpt-config-sync#975]
In 1.16 the rootsync secret is changed to add the prefix of the reconcilerName. 
[reconcilerName](https://github.com/GoogleContainerTools/kpt-config-sync/blame/v1.16/pkg/reconcilermanager/controllers/rootsync_controller.go#L749)
This change broker our config sync because the combined name is longer than 63. But it was never mentioned in the release notes. We had to trace the code to figure that out.

**Comment by mikebz** [comment]
Sorry about that.  We try to catch as much as the changing things as possible.  The API changes are detected by the CI, but some of these other things like name change are hard to catch w/o a specific test.
